- name: Converge
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Gather required subset of facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - 'architecture'
          - 'system'

  roles:
    - role: wzzrd.ghdl.starship
      vars:
        starship_version: 1.18.0
        downloader_github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
