- name: Verify
  hosts: all
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false

  tasks:
    - name: Check if starship binary exists
      block:
        - name: Check for existence for /usr/local/bin/starship
          ansible.builtin.stat:
            path: /usr/local/bin/starship
          register: starship_stat_result

        - name: Verify result of previous task
          ansible.builtin.assert:
            that:
              - starship_stat_result.stat.exists

        - name: Verify we can start starship
          ansible.builtin.command:
            cmd: starship --version
          changed_when: false
